version: "3.3"
services:
  web:
    image: mental/authentication
    build: .
    ports:
      - "10020:10020"
    links:
      - cont_postgresql
    depends_on:
      - cont_postgresql
    environment:
      SPRING_PROFILES_ACTIVE: default
  cont_postgresql:
    image: sameersbn/postgresql
    ports:
      - "5432:5432"
    environment:
      DB_NAME: authentication-dev,authentication-qa
      DB_USER: dbuser
      DB_PASS: 12345

