spring:
  datasource:
    url: jdbc:postgresql://${connection:localhost}:5432/authentication-dev
    username: dbuser
    password: 12345
  thymeleaf:
    cache: false
  jpa:
    show-sql: true

liquibase:
  drop-first: true
  context: test