liquibase:
  change-log: classpath:/db/db.changelog.xml

server:
  port: 10002
  contextPath: /authentication
  ssl:
    enabled: true
    key-store: classpath:keystore/thekeystore.jks
    key-store-password: changeit

logging:
  level:
    root: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect